build: swap two linker arguments, to enable compilation on Cygwin
Since nano-8.1 (which moved to gettext-0.20), compiling on Cygwin
failed with: "undefined reference to `libintl_dgettext'".  Avoid
this by moving the '-lintl' argument to after the gnulib one.

Reported-by: Philippe Baril Lecavalier <pbl.ltx@gmail.com>